apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dumblogger
  name: dumblogger
  namespace: kafka-connect
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dumblogger
  template:
    metadata:
      labels:
        app: dumblogger
      annotations:
        underworld.logtopic: somedumbtopic 
    spec:
      containers:
        - name: dumblogger
          image: walmartdigital/dumblogger:0.0.3
          imagePullPolicy: IfNotPresent
          env:
          - name: LOGTOPIC
            value: "_dumblogger.logs"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: '0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: dumblogger
  namespace: kafka-connect
  labels:
    app: dumblogger
spec:
  ports:
    - port: 3000
      name: server
  type: NodePort
  selector:
    app: dumblogger
