apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafdrop
  name: kafdrop
  namespace: kafka-connect
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:3.23.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERCONNECT
              value: 'kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092'
            - name: JVM_OPTS
              value: -Xms256m -Xmx256m
            - name: SERVER_SERVLET_CONTEXTPATH
              value: '/'
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: '0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: kafka-connect
  labels:
    app: kafdrop
spec:
  ports:
    - port: 9000
      name: server
  type: NodePort
  selector:
    app: kafdrop
