apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: kafka-connect
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:6.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_HOSTS
              value: 'http://elasticsearch-master.default.svc.cluster.local:9200'
          ports:
            - containerPort: 5601
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: '0.5'
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kafka-connect
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      name: server
  type: NodePort
  selector:
    app: kibana
